import { ethers } from "hardhat";

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying contracts with the account:", deployer.address);

  // Deploy CredentialRegistry
  const CredentialRegistry = await ethers.getContractFactory("CredentialRegistry");
  const credentialRegistry = await CredentialRegistry.deploy(deployer.address);
  await credentialRegistry.waitForDeployment();
  const credentialRegistryAddress = await credentialRegistry.getAddress();
  console.log("CredentialRegistry deployed to:", credentialRegistryAddress);

  // Deploy RevocationRegistry
  const RevocationRegistry = await ethers.getContractFactory("RevocationRegistry");
  const revocationRegistry = await RevocationRegistry.deploy(deployer.address);
  await revocationRegistry.waitForDeployment();
  const revocationRegistryAddress = await revocationRegistry.getAddress();
  console.log("RevocationRegistry deployed to:", revocationRegistryAddress);

  // We skip ZKVerifier deployment here since we use snarkjs verify on frontend for demo
  // Or we could deploy a verifier generated by snarkjs if we wanted fully on-chain verification.
  // For the hackathon demo, we will verify off-chain or generate verifier.sol and deploy it.
  
  // Authorize deployer as issuer and revoker for demo purposes
  await credentialRegistry.setIssuerStatus(deployer.address, true);
  await revocationRegistry.setRevokerStatus(deployer.address, true);
  console.log("Deployer authorized as Issuer and Revoker");

  console.log("\nUpdate your .env file with:");
  console.log(`NEXT_PUBLIC_CREDENTIAL_REGISTRY_ADDRESS="${credentialRegistryAddress}"`);
  console.log(`NEXT_PUBLIC_REVOCATION_REGISTRY_ADDRESS="${revocationRegistryAddress}"`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
